version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: androidx.navigation:navigation-fragment-ktx
    versions:
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-safe-args-gradle-plugin
    versions:
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-ui-ktx
    versions:
    - 2.3.4
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.31
  - dependency-name: androidx.lifecycle:lifecycle-viewmodel-ktx
    versions:
    - 2.3.0
  - dependency-name: androidx.lifecycle:lifecycle-livedata-ktx
    versions:
    - 2.3.0
